version: '3'

networks:
  monitor_monitoring:
    external:
      name: monitor_monitoring

services:
  nginx:
    image: hanzel/nginx-html
    networks:
      - default
      - monitor_monitoring
    ports:
      - "8888:80"
    deploy:
      replicas: 5
