version: '3'

networks:
  monitor_monitoring:
    external:
      name: monitor_monitoring

services:
  whoami:
    image: emilevauge/whoami
    networks:
      - default
      - monitor_monitoring
    expose:
      - '7001'
    ports:
      - '7001:80'
    deploy:
      mode: global
