version: '3'

networks:
  monitor_monitoring:
    external: true

# source: https://github.com/influxdata/TICK-docker/blob/master/1.3/docker-compose.yml
services:
  # Define a service for using the influx CLI tool.
  # docker-compose run influxdb-cli
  influxdb-cli:
    image: influxdb
    entrypoint:
      - influx
      - -host
      - influxdb
    links:
      - influxdb
