version: '3'

networks:
  monitor_monitoring:
    external:
      name: monitor_monitoring

# portainer-ssl/portainer-ssl.yml
# source: https://github.com/Blaiserman/swarm-mode-init-script/blob/cb7f3594849aca244035934baf5f48837c116a20/compose/portainer-ssl/portainer-ssl.yml

# docker service create \
# 	-d \
#     --name portainer \
#     --publish 9000:9000 \
#     --constraint 'node.role == manager' \
#     --mount type=bind,src=//var/run/docker.sock,dst=/var/run/docker.sock \
# 	--mount type=bind,src=$$PWD/data,dst=/data \
#     portainer/portainer

# source: https://medium.com/technoetics/creating-simple-docker-swarm-management-ui-using-portainer-and-reactjs-bd32afbdb1b9
# TODO: Try Me
# docker run -d -p 9000:9000 --privileged -v /var/run/docker.sock:/var/run/docker.sock portainer/portainer

services:
  portainer:
    image: portainer/portainer
    # command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    networks:
      - default
      - monitor_monitoring
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      # labels:
      #   - com.df.notify=true
      #   - com.df.distribute=true
      #   - com.df.port=9000
      #   - com.df.servicePath=/#/auth
      #   - "traefik.port=9000"
      #   - "traefik.frontend.rule=Host:mydomain.lan;PathPrefixStrip:/portainer"
      #   - "traefik.docker.network=proxy"
    # depends_on:
    #   - proxy

# ------------------------------------------------------------------------------------

  # source: https://github.com/ecozoic/mern-starter/blob/20ddcc4453fecf80cac3e7b703d1f0382dcba43a/docker-compose.yml
  # portainer:
  #   image: portainer/portainer
  #   container_name: portainer
  #   command: --no-auth
  #   ports:
  #     - 9000:9000
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - data_portainer:/data


# ------------------------------------------------------------------------------------

# source: https://github.com/btyh17mxy/portainerNodeMonitor/blob/d7b5799c352f71cc97cae0047768868b494d17b7/docker-compose-example.yml
# version: "3"
# services:

#   portainer:
#     image: portainer/portainer
#     ports:
#       - "9000:9000"
#     stop_grace_period: 1m30s
#     volumes:
#       - endpoints:/etc/endpoints
#       - /var/run/docker.sock:/var/run/docker.sock
#     command: ['--external-endpoints', '/etc/endpoints/endpoints.json']
#     depends_on:
#       - node-monitor
#     deploy:
#       placement:
#         constraints: [node.role == manager]
#   node-monitor:
#     image: btyh17mxy/portainernodemonitor
#     volumes:
#       - endpoints:/etc/endpoints
#       - /var/run/docker.sock:/var/run/docker.sock
#     deploy:
#       placement:
#         constraints: [node.role == manager]
# volumes:
#   endpoints:
