# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# DISABLED ## Load and evaluate rules in this file every 'evaluation_interval' seconds.
# DISABLED #rule_files:
# DISABLED #  - "alert.rules"
# DISABLED #  # - "first.rules"
# DISABLED #  # - "second.rules"

# source: https://github.com/juliusv/prometheus_docker_demo/blob/master/prometheus.yml
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    dns_sd_configs:
      - names: ['tasks.node-exporter']
        type: A
        port: 9100
  - job_name: 'cadvisor'
    dns_sd_configs:
      - names: ['tasks.cadvisor']
        type: A
        port: 8080
  - job_name: 'docker-engine'
    dns_sd_configs:
      - names: ['tasks.docker-exporter']
        type: A
        port: 4999
        # port: 4998


    # Override the global default and scrape targets from this job every 5 seconds.
    # scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    # static_configs:
    #      - targets: ['localhost:9090','cadvisor:8080','node-exporter:9100']
