# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:5.6.1

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>

# COPY ./plugins /plugins

# RUN kibana-plugin install file:///plugins/logtrail-5.6.1-0.1.21.zip
