# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:5.6.2

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>

RUN kibana-plugin install https://github.com/sivasamyk/logtrail/releases/download/v0.1.21/logtrail-5.6.1-0.1.21.zip
